// GENERATED — do not edit by hand.
// Source: backend OpenAPI spec at /api/v1/openapi.json (see backend/app/main.py).
// Regenerate types from the committed spec: `pnpm run codegen`.
// Re-export the spec from the backend and regenerate:
//   `pnpm run codegen:export && pnpm run codegen`.
// CI enforces drift via `pnpm run codegen:check`.
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/admin/audit-log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Query Audit Log
         * @description Cursor-paginated audit-log query, descending by ``event_position``.
         */
        get: operations["query_audit_log_api_v1_admin_audit_log_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/audit-log/export.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export Audit Log Csv
         * @description Stream the audit log as CSV. Same filters as the JSON endpoint.
         */
        get: operations["export_audit_log_csv_api_v1_admin_audit_log_export_csv_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/events/verify-chain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify Chain
         * @description Walk the event log in ``position`` order and recompute every hash.
         *
         *     Window-bounded: ``to_position - from_position`` may not exceed 1M.
         *     Returns ``ok=true`` for a clean chain, otherwise ``ok=false`` with
         *     the position where the chain first breaks.
         */
        get: operations["verify_chain_api_v1_admin_events_verify_chain_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/admin/reference-sequences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Reference Sequences
         * @description Return every ``(prefix, year, last_value)`` row, sorted by
         *     ``(prefix, year)``.
         */
        get: operations["list_reference_sequences_api_v1_admin_reference_sequences_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refresh */
        post: operations["refresh_api_v1_auth_refresh_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Materials */
        get: operations["list_materials_api_v1_materials_get"];
        put?: never;
        /** Create Material */
        post: operations["create_material_api_v1_materials_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Material */
        get: operations["get_material_api_v1_materials__material_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Material */
        patch: operations["update_material_api_v1_materials__material_id__patch"];
        trace?: never;
    };
    "/api/v1/materials/{material_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Material */
        post: operations["archive_material_api_v1_materials__material_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}/receipts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Receipts */
        get: operations["list_receipts_api_v1_materials__material_id__receipts_get"];
        put?: never;
        /** Record Receipt */
        post: operations["record_receipt_api_v1_materials__material_id__receipts_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/materials/{material_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Material */
        post: operations["unarchive_material_api_v1_materials__material_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Rates */
        get: operations["list_rates_api_v1_rates_get"];
        put?: never;
        /** Create Rate */
        post: operations["create_rate_api_v1_rates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates/{rate_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Rate */
        get: operations["get_rate_api_v1_rates__rate_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Rate */
        patch: operations["update_rate_api_v1_rates__rate_id__patch"];
        trace?: never;
    };
    "/api/v1/rates/{rate_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Rate */
        post: operations["archive_rate_api_v1_rates__rate_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates/{rate_id}/set-default": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set Default Rate */
        post: operations["set_default_rate_api_v1_rates__rate_id__set_default_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rates/{rate_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Rate */
        post: operations["unarchive_rate_api_v1_rates__rate_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Settings
         * @description Return every registered setting, merged with schema defaults.
         */
        get: operations["list_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/{key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Setting
         * @description Return a single setting by key. 400 on unknown key.
         */
        get: operations["get_setting_api_v1_settings__key__get"];
        /**
         * Put Setting
         * @description Validate and persist a single setting. Emits SettingChanged.
         */
        put: operations["put_setting_api_v1_settings__key__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings:bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk Update Settings
         * @description Atomic batch update. One invalid value rolls back everything.
         */
        post: operations["bulk_update_settings_api_v1_settings_bulk_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Supplies */
        get: operations["list_supplies_api_v1_supplies_get"];
        put?: never;
        /** Create Supply */
        post: operations["create_supply_api_v1_supplies_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplies/{supply_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Supply */
        get: operations["get_supply_api_v1_supplies__supply_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Supply */
        patch: operations["update_supply_api_v1_supplies__supply_id__patch"];
        trace?: never;
    };
    "/api/v1/supplies/{supply_id}/archive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Archive Supply */
        post: operations["archive_supply_api_v1_supplies__supply_id__archive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/supplies/{supply_id}/unarchive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Unarchive Supply */
        post: operations["unarchive_supply_api_v1_supplies__supply_id__unarchive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Users */
        get: operations["list_users_api_v1_users_get"];
        put?: never;
        /** Create User */
        post: operations["create_user_api_v1_users_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get User */
        get: operations["get_user_api_v1_users__user_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update User */
        patch: operations["update_user_api_v1_users__user_id__patch"];
        trace?: never;
    };
    "/api/v1/users/{user_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate User */
        post: operations["deactivate_user_api_v1_users__user_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reactivate User */
        post: operations["reactivate_user_api_v1_users__user_id__reactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/users/{user_id}/reset-password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reset Password */
        post: operations["reset_password_api_v1_users__user_id__reset_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness + DB reachability probe.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AuditLogResponse
         * @description Paginated list response. ``next_cursor`` is an opaque base64 token
         *     that, when passed back, resumes pagination just past the last returned
         *     row. ``null`` when the list is exhausted.
         */
        AuditLogResponse: {
            /** Items */
            items: components["schemas"]["AuditLogRow"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * AuditLogRow
         * @description One row in the audit_log read model, as returned by the query API.
         */
        AuditLogRow: {
            /** Actor Email */
            actor_email: string | null;
            /** Actor Role */
            actor_role: string | null;
            /** Actor User Id */
            actor_user_id: string | null;
            /**
             * Aggregate Id
             * Format: uuid
             */
            aggregate_id: string;
            /** Aggregate Type */
            aggregate_type: string;
            /** Event Id */
            event_id: string | null;
            /** Event Position */
            event_position: number;
            /** Event Type */
            event_type: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Ip Address */
            ip_address: string | null;
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
            /** Payload Excerpt */
            payload_excerpt: {
                [key: string]: unknown;
            } | null;
            /** Summary */
            summary: string;
        };
        /**
         * BulkSettingUpdateRequest
         * @description POST body for a batch update.
         *
         *     The request is all-or-nothing: if any value fails validation, no
         *     writes happen.
         */
        BulkSettingUpdateRequest: {
            /** Updates */
            updates: {
                [key: string]: unknown;
            };
        };
        /**
         * BulkSettingUpdateResponse
         * @description Response for a successful batch update.
         *
         *     ``updated`` mirrors the request keys with their validated (typed)
         *     values as returned by the service.
         */
        BulkSettingUpdateResponse: {
            /** Updated */
            updated: {
                [key: string]: unknown;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoginRequest */
        LoginRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Password */
            password: string;
        };
        /** LogoutRequest */
        LogoutRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /** MaterialCreateRequest */
        MaterialCreateRequest: {
            /** Brand */
            brand?: string | null;
            /** Color */
            color?: string | null;
            /** Density G Per Cm3 */
            density_g_per_cm3?: number | string | null;
            /** Material Type */
            material_type: string;
            /** Name */
            name: string;
        };
        /**
         * MaterialDetailResponse
         * @description Material + the most recent 10 receipts (newest first).
         */
        MaterialDetailResponse: {
            /** Brand */
            brand?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Cost Per Gram */
            current_cost_per_gram: string;
            /** Density G Per Cm3 */
            density_g_per_cm3?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Archived */
            is_archived: boolean;
            /** Material Type */
            material_type: string;
            /** Name */
            name: string;
            /** On Hand Grams */
            on_hand_grams: string;
            /** Recent Receipts */
            recent_receipts?: components["schemas"]["MaterialReceiptResponse"][];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** MaterialListResponse */
        MaterialListResponse: {
            /** Items */
            items: components["schemas"]["MaterialResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** MaterialReceiptCreateRequest */
        MaterialReceiptCreateRequest: {
            /** Grams */
            grams: number | string;
            /** Notes */
            notes?: string | null;
            /** Reference */
            reference?: string | null;
            /** Total Cost */
            total_cost: number | string;
            /** Vendor */
            vendor?: string | null;
        };
        /** MaterialReceiptListResponse */
        MaterialReceiptListResponse: {
            /** Items */
            items: components["schemas"]["MaterialReceiptResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** MaterialReceiptResponse */
        MaterialReceiptResponse: {
            /** Grams */
            grams: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Material Id
             * Format: uuid
             */
            material_id: string;
            /** Notes */
            notes?: string | null;
            /**
             * Received At
             * Format: date-time
             */
            received_at: string;
            /** Reference */
            reference?: string | null;
            /** Total Cost */
            total_cost: string;
            /** Unit Cost At Receipt */
            unit_cost_at_receipt: string;
            /** Vendor */
            vendor?: string | null;
        };
        /** MaterialResponse */
        MaterialResponse: {
            /** Brand */
            brand?: string | null;
            /** Color */
            color?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Current Cost Per Gram */
            current_cost_per_gram: string;
            /** Density G Per Cm3 */
            density_g_per_cm3?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Archived */
            is_archived: boolean;
            /** Material Type */
            material_type: string;
            /** Name */
            name: string;
            /** On Hand Grams */
            on_hand_grams: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /**
         * MaterialUpdateRequest
         * @description PATCH-style — only fields the user wants to change.
         */
        MaterialUpdateRequest: {
            /** Brand */
            brand?: string | null;
            /** Color */
            color?: string | null;
            /** Density G Per Cm3 */
            density_g_per_cm3?: number | string | null;
            /** Material Type */
            material_type?: string | null;
            /** Name */
            name?: string | null;
        };
        /** MeResponse */
        MeResponse: {
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            role: components["schemas"]["Role"];
        };
        /** PasswordResetResponse */
        PasswordResetResponse: {
            /** Generated Password */
            generated_password: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
        };
        /** RateCreateRequest */
        RateCreateRequest: {
            /** Applies To Printer Id */
            applies_to_printer_id?: string | null;
            /**
             * Is Default For Kind
             * @default false
             */
            is_default_for_kind: boolean;
            kind: components["schemas"]["RateKind"];
            /** Name */
            name: string;
            /** Value */
            value: number | string;
        };
        /**
         * RateKind
         * @enum {string}
         */
        RateKind: "labor" | "machine" | "overhead";
        /** RateListResponse */
        RateListResponse: {
            /** Items */
            items: components["schemas"]["RateResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** RateResponse */
        RateResponse: {
            /** Applies To Printer Id */
            applies_to_printer_id?: string | null;
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Archived */
            is_archived: boolean;
            /** Is Default For Kind */
            is_default_for_kind: boolean;
            kind: components["schemas"]["RateKind"];
            /** Name */
            name: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Value */
            value: string;
        };
        /**
         * RateUpdateRequest
         * @description PATCH-style — only fields the user wants to change.
         *
         *     ``is_default_for_kind`` is intentionally not editable here; use the
         *     dedicated ``set-default`` endpoint to flip it atomically.
         */
        RateUpdateRequest: {
            /** Applies To Printer Id */
            applies_to_printer_id?: string | null;
            /** Name */
            name?: string | null;
            /** Value */
            value?: number | string | null;
        };
        /**
         * ReferenceSequenceRow
         * @description A single ``reference_sequence`` row, surfaced via the admin API.
         */
        ReferenceSequenceRow: {
            /** Last Value */
            last_value: number;
            /** Prefix */
            prefix: string;
            /** Year */
            year: number;
        };
        /** RefreshRequest */
        RefreshRequest: {
            /** Refresh Token */
            refresh_token: string;
        };
        /**
         * Role
         * @description RBAC roles. Deny-by-default; presence in a `require_role` allowlist
         *     is the only thing that grants access.
         * @enum {string}
         */
        Role: "owner" | "bookkeeper" | "production" | "sales" | "viewer";
        /**
         * SettingResponse
         * @description One setting, merged with its schema default and provenance.
         */
        SettingResponse: {
            /** Default */
            default: unknown;
            /** Key */
            key: string;
            /**
             * Schema Type
             * @description Friendly Python type name for the value (e.g. 'Decimal', 'str', 'dict'). Used by the frontend to pick an editor.
             */
            schema_type: string;
            /**
             * Updated At
             * @description When the row was last written. None if no row exists yet.
             */
            updated_at?: string | null;
            /**
             * Updated By User Id
             * @description User who last wrote the row. None if from default.
             */
            updated_by_user_id?: string | null;
            /** Value */
            value: unknown;
        };
        /**
         * SettingUpdateRequest
         * @description PUT body for a single setting.
         */
        SettingUpdateRequest: {
            /** Value */
            value: unknown;
        };
        /** SupplyCreateRequest */
        SupplyCreateRequest: {
            /** Name */
            name: string;
            /**
             * On Hand
             * @default 0
             */
            on_hand: number | string;
            /** Unit */
            unit: string;
            /** Unit Cost */
            unit_cost: number | string;
            /** Vendor */
            vendor?: string | null;
        };
        /** SupplyListResponse */
        SupplyListResponse: {
            /** Items */
            items: components["schemas"]["SupplyResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** SupplyResponse */
        SupplyResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Archived */
            is_archived: boolean;
            /** Name */
            name: string;
            /** On Hand */
            on_hand: string;
            /** Unit */
            unit: string;
            /** Unit Cost */
            unit_cost: string;
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
            /** Vendor */
            vendor?: string | null;
        };
        /**
         * SupplyUpdateRequest
         * @description PATCH-style — only fields the user wants to change.
         */
        SupplyUpdateRequest: {
            /** Name */
            name?: string | null;
            /** Unit */
            unit?: string | null;
            /** Unit Cost */
            unit_cost?: number | string | null;
            /** Vendor */
            vendor?: string | null;
        };
        /** TokenPair */
        TokenPair: {
            /** Access Token */
            access_token: string;
            /** Expires In */
            expires_in: number;
            /** Refresh Token */
            refresh_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** UserCreateRequest */
        UserCreateRequest: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Full Name */
            full_name: string;
            role: components["schemas"]["Role"];
        };
        /**
         * UserCreateResponse
         * @description Same as UserResponse but carries the freshly-generated password.
         *
         *     The password appears in the response body exactly once — there is no
         *     other surface that returns it. The router never logs it.
         */
        UserCreateResponse: {
            /** Generated Password */
            generated_password: string;
            user: components["schemas"]["UserResponse"];
        };
        /** UserListResponse */
        UserListResponse: {
            /** Items */
            items: components["schemas"]["UserResponse"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /**
         * UserResponse
         * @description Single user, as returned by GET /users and PATCH /users/{id}.
         */
        UserResponse: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Email */
            email: string;
            /** Full Name */
            full_name: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Is Active */
            is_active: boolean;
            /** Last Login */
            last_login?: string | null;
            role: components["schemas"]["Role"];
            /**
             * Updated At
             * Format: date-time
             */
            updated_at: string;
        };
        /** UserUpdateRequest */
        UserUpdateRequest: {
            /** Full Name */
            full_name?: string | null;
            /** Is Active */
            is_active?: boolean | null;
            role?: components["schemas"]["Role"] | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerifyChainResponse
         * @description Result of ``GET /admin/events/verify-chain``.
         *
         *     ``ok=True`` means every event's recomputed hash matches what we stored
         *     and every ``prev_event_hash`` matches the previous row's
         *     ``event_hash``. ``broken_at_position`` is the first position where
         *     the chain fails.
         */
        VerifyChainResponse: {
            /**
             * Broken At Position
             * @description First position where verification failed (None if ok=True).
             */
            broken_at_position?: number | null;
            /**
             * Events Checked
             * @default 0
             */
            events_checked: number;
            /**
             * Last Position
             * @description Last position the verifier successfully validated.
             */
            last_position?: number | null;
            /** Ok */
            ok: boolean;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    query_audit_log_api_v1_admin_audit_log_get: {
        parameters: {
            query?: {
                actor_user_id?: string | null;
                event_type?: string | null;
                aggregate_type?: string | null;
                aggregate_id?: string | null;
                from?: string | null;
                to?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditLogResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    export_audit_log_csv_api_v1_admin_audit_log_export_csv_get: {
        parameters: {
            query?: {
                actor_user_id?: string | null;
                event_type?: string | null;
                aggregate_type?: string | null;
                aggregate_id?: string | null;
                from?: string | null;
                to?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_chain_api_v1_admin_events_verify_chain_get: {
        parameters: {
            query?: {
                from_position?: number;
                to_position?: number | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VerifyChainResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_reference_sequences_api_v1_admin_reference_sequences_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReferenceSequenceRow"][];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
        };
    };
    refresh_api_v1_auth_refresh_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RefreshRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenPair"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_materials_api_v1_materials_get: {
        parameters: {
            query?: {
                search?: string | null;
                is_archived?: boolean | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_material_api_v1_materials_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_material_api_v1_materials__material_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialDetailResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_material_api_v1_materials__material_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_material_api_v1_materials__material_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_receipts_api_v1_materials__material_id__receipts_get: {
        parameters: {
            query?: {
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialReceiptListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_receipt_api_v1_materials__material_id__receipts_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MaterialReceiptCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_material_api_v1_materials__material_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_rates_api_v1_rates_get: {
        parameters: {
            query?: {
                kind?: components["schemas"]["RateKind"] | null;
                is_archived?: boolean | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_rate_api_v1_rates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rate_api_v1_rates__rate_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_rate_api_v1_rates__rate_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rate_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RateUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_rate_api_v1_rates__rate_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_default_rate_api_v1_rates__rate_id__set_default_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_rate_api_v1_rates__rate_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                rate_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"][];
                };
            };
        };
    };
    get_setting_api_v1_settings__key__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_setting_api_v1_settings__key__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    bulk_update_settings_api_v1_settings_bulk_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BulkSettingUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BulkSettingUpdateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_supplies_api_v1_supplies_get: {
        parameters: {
            query?: {
                search?: string | null;
                is_archived?: boolean | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_supply_api_v1_supplies_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplyCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_supply_api_v1_supplies__supply_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supply_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_supply_api_v1_supplies__supply_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supply_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SupplyUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_supply_api_v1_supplies__supply_id__archive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supply_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unarchive_supply_api_v1_supplies__supply_id__unarchive_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                supply_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_users_api_v1_users_get: {
        parameters: {
            query?: {
                search?: string | null;
                role?: components["schemas"]["Role"] | null;
                is_active?: boolean | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_user_api_v1_users_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserCreateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_user_api_v1_users__user_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_user_api_v1_users__user_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserUpdateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_user_api_v1_users__user_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reactivate_user_api_v1_users__user_id__reactivate_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    reset_password_api_v1_users__user_id__reset_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                user_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PasswordResetResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
