#!/usr/bin/env bash
# Generate .env.dev from .env.dev.example, substituting locally-safe random
# values for any placeholder sentinels. Idempotent: refuses to overwrite an
# existing .env.dev. Values are LOCAL DEV ONLY — do not reuse anywhere else.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$repo_root"

target=".env.dev"
template=".env.dev.example"

if [ -f "$target" ]; then
    echo "gen_env_dev: $target already exists; leaving it alone."
    exit 0
fi

if [ ! -f "$template" ]; then
    echo "gen_env_dev: $template not found." >&2
    exit 1
fi

command -v openssl >/dev/null 2>&1 || {
    echo "gen_env_dev: openssl is required." >&2
    exit 1
}

jwt_secret="$(openssl rand -hex 32)"
db_password="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
owner_password="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
# .local is a reserved special-use TLD (RFC 6761, mDNS) and the
# email-validator library backing pydantic's EmailStr rejects it. Using
# example.com — an IANA-reserved documentation domain that the validator
# explicitly allows — keeps logins working without hitting a real domain.
owner_email="owner@example.com"

tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
    cat <<EOF
# LOCAL DEV ONLY — DO NOT REUSE THESE VALUES ANYWHERE ELSE.
# Generated by scripts/gen_env_dev.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ).
# Delete this file and re-run \`make bootstrap\` to regenerate.

EOF
    # Walk the template line by line; substitute known placeholders.
    while IFS= read -r line || [ -n "$line" ]; do
        case "$line" in
            JWT_SECRET_KEY=*)
                echo "JWT_SECRET_KEY=$jwt_secret"
                ;;
            POSTGRES_PASSWORD=*)
                echo "POSTGRES_PASSWORD=$db_password"
                ;;
            DATABASE_URL=*)
                # Keep the template's host/db/user but swap the password.
                echo "DATABASE_URL=postgresql+asyncpg://voxel:$db_password@db:5432/voxel_ledger"
                ;;
            *)
                echo "$line"
                ;;
        esac
    done < "$template"

    # Append owner credentials for seed_owner.py.
    cat <<EOF

# ---- Seed owner ----
# Consumed by scripts/seed_owner.py the first time the stack comes up.
OWNER_EMAIL=$owner_email
OWNER_PASSWORD=$owner_password
EOF
} > "$tmp"

mv "$tmp" "$target"
chmod 600 "$target"
trap - EXIT

echo "gen_env_dev: wrote $target"
echo "  owner email:    $owner_email"
echo "  owner password: $owner_password"
